# Build stage
FROM node:20-alpine as build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

# Serve stage
FROM nginx:stable-alpine

# 👇 FIXED: use /app/dist instead of /app/build
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
