services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"

  genai:
    build:
      context: ./genai
    ports:
      - "5000:5000"
    environment:
      - GROQ_API_KEY
      - MONGO_URI
      - MONGO_RETRY_MS
      - MONGO_RETRY_ATTEMPT
      - DATABASE_NAME
      - GROQ_MODEL
