FROM python:3.12.11-slim

WORKDIR /app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 3000

RUN useradd app
USER app

CMD [ "uvicorn","main:app","--host","0.0.0.0","--port","3000" ]