# genai/Dockerfile

FROM python:3.12.11-slim

WORKDIR /app
COPY . .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 7000

RUN adduser -D app
USER app


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7000"]
