# genai/Dockerfile

FROM python:3.12.11-slim

WORKDIR /app
COPY . .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 7000



CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7000"]
