name: Chatbot

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/rsa
          chmod 600 ~/.ssh/rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Verify & install rsync on Remote Server
        run: |
          ssh -i ~/.ssh/rsa ${{ secrets.VM_USER }}@${{ secrets.SERVER_IP }} \
          "command -v rsync >/dev/null 2>&1 || (sudo apt-get update && sudo apt-get install -y rsync)"

      - name: Sync files to Server
        run: |
          rsync -avzh -e 'ssh -i ~/.ssh/rsa' \
            --exclude=.git ./ ${{ secrets.VM_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.VM_USER }}/app

      - name: Build and Restart Docker service on VM
        run: |
          ssh -i ~/.ssh/rsa ${{ secrets.VM_USER }}@${{ secrets.SERVER_IP }} << EOF
            cd /home/${{ secrets.VM_USER }}/app
            docker compose down

            CONTAINERS=$(docker ps -aq)
            if [ -n "$CONTAINERS" ]; then
              docker rm -f $CONTAINERS
            fi
            
            IMAGES=$(docker images -q)
            if [ -n "$IMAGES" ]; then
              docker rmi -f $IMAGES
            fi
            docker compose build --no-cache
            docker compose up -d
          EOF
